# suppress inspection "UnusedProperty" for whole file
server.port=8081
server.servlet.session.timeout=3600

# sqlite db name
spring.datasource.url=jdbc:sqlite:comments-tree.db

logging.level.root=info
logging.level.org.springframework.web=info

spring.auto.openurl=false
spring.web.loginurl=http://localhost:8081/index.html

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.info.env.enabled=true
info.app.name=comments-tree
info.app.version=1.0.0
