server.port=8081
server.servlet.session.timeout=3600
#server.servlet.session.timeout=36

# sqlite db name
spring.datasource.url=jdbc:sqlite:comments-tree.db

logging.level.root=debug
logging.level.org.springframework.web=debug

spring.auto.openurl=true
spring.web.loginurl=http://localhost:8081/index.html